(function () {
  'use strict';
  var SITE = 'www_metaimperiya_com';
  var base = window.location.origin;
  var categories = ['news','video','music','games','sport','cinema','programming','business','dating'];
  function escapeHtml(v){var d=document.createElement('div');d.textContent=v||'';return d.innerHTML;}
  function date(v){return new Date(v || Date.now()).toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'});}
  function path(){return window.location.pathname.replace(/^\/+|\/+$/g,'').split('/').filter(Boolean);}
  function setMeta(article){var url=base+'/'+article.category+'/'+article.slug+'/';document.title=article.title+' — METAIMPERIYA';document.querySelector('link[rel="canonical"]').href=url;var robots=document.querySelector('meta[name="robots"]');if(robots)robots.content='index,follow';[['description',article.description],['og:title',article.title],['og:description',article.description],['og:url',url],['og:image',article.coverUrl||base+'/assets/images/metaimperiya-512x512.png']].forEach(function(x){var el=document.querySelector('meta['+(x[0].indexOf('og:')===0?'property':'name')+'="'+x[0]+'"]');if(el)el.content=x[1]||'';});}
  function firebaseReady(cb){if(window.firebase)return cb();setTimeout(function(){firebaseReady(cb);},30);}
  function renderCards(items, root){if(!items.length){root.innerHTML='<div class="empty-state"><strong>Материалов пока нет</strong><br>Новые публикации этого раздела появятся здесь.</div>';return;}root.innerHTML=items.map(function(a){return '<article class="article-card">'+(a.coverUrl?'<img src="'+escapeHtml(a.coverUrl)+'" alt="">':'')+'<div class="article-card__body"><time datetime="'+new Date(a.publishedAt).toISOString()+'">'+date(a.publishedAt)+'</time><h2><a href="/'+a.category+'/'+a.slug+'/">'+escapeHtml(a.title)+'</a></h2><p>'+escapeHtml(a.description)+'</p><a class="button" href="/'+a.category+'/'+a.slug+'/">Читать</a></div></article>';}).join('');}
  function loadCategory(category){firebaseReady(function(){firebase.database().ref('sites/'+SITE+'/articles').orderByChild('category').equalTo(category).once('value').then(function(s){var list=[];s.forEach(function(c){var a=c.val();if(a.status==='published'){a.id=c.key;list.push(a);}});list.sort(function(a,b){return(b.publishedAt||0)-(a.publishedAt||0);});renderCards(list,document.getElementById('articles'));});});}
  function loadArticle(category,slug){firebaseReady(function(){firebase.database().ref('sites/'+SITE+'/article_slugs/'+category+'/'+slug).once('value').then(function(s){var id=s.val();if(!id)return null;return firebase.database().ref('sites/'+SITE+'/articles/'+id).once('value');}).then(function(s){if(!s){throw new Error('not found');}var a=s.val();if(!a||a.status!=='published'||a.category!==category){throw new Error('not found');}a.id=s.key;setMeta(a);var root=document.getElementById('article');root.innerHTML='<p class="article-meta">'+date(a.publishedAt)+' · '+escapeHtml(a.category)+'</p><h1>'+escapeHtml(a.title)+'</h1>'+(a.coverUrl?'<img class="article-cover" src="'+escapeHtml(a.coverUrl)+'" alt="'+escapeHtml(a.title)+'">':'')+'<div class="article-body">'+(a.content||'')+'</div><section class="share-box"><h2>Поделиться в ленте METAIMPERIYA</h2><p>Опубликуйте карточку статьи у себя в ленте.</p><button class="button" id="shareArticle">Поделиться в ленте</button></section><section class="comments-box"><h2>Комментарии</h2><div id="comments"></div><div class="comment-form"><input id="commentText" placeholder="Написать комментарий"><button class="button" id="sendComment">Отправить</button></div></section>';document.getElementById('shareArticle').onclick=function(){share(a);};initComments(a);}).catch(function(){document.title='Материал не найден — METAIMPERIYA';document.getElementById('article').innerHTML='<h1>Материал не найден</h1><p class="content-lead">Возможно, он ещё не опубликован или был удалён.</p>';});});}
  function share(a){var u=firebase.auth().currentUser;if(!u){window.location.href='/?returnTo='+encodeURIComponent(location.href);return;}var post={author:u.displayName||u.email||'METAIMPERIYA',authorUid:u.uid,authorAvatar:u.photoURL||null,text:a.title,timestamp:Date.now(),likes:0,commentCount:0,reposts:0,articleId:a.id,articleUrl:'/'+a.category+'/'+a.slug+'/',articleTitle:a.title,articleDescription:a.description,articleCover:a.coverUrl||null,deleted:null},id=firebase.database().ref('sites/'+SITE+'/feed_posts').push().key,updates={};updates['sites/'+SITE+'/feed_posts/'+id]=post;updates['sites/'+SITE+'/user_posts/'+u.uid+'/'+id]=post;firebase.database().ref().update(updates).then(function(){alert('Карточка опубликована в вашей ленте.');});}
  function initComments(a){var target=document.getElementById('comments'),send=document.getElementById('sendComment');if(!a.feedPostId){target.innerHTML='<p class="article-meta">Комментарии будут доступны после публикации карточки в ленте.</p>';send.disabled=true;return;}var ref=firebase.database().ref('sites/'+SITE+'/feed_posts/'+a.feedPostId+'/comments');ref.on('value',function(s){var html='';s.forEach(function(c){var x=c.val();html+='<div class="comment"><strong>'+escapeHtml(x.author||'Пользователь')+'</strong><br>'+escapeHtml(x.text)+'<br><small>'+date(x.timestamp)+'</small></div>';});target.innerHTML=html||'<p class="article-meta">Комментариев пока нет.</p>';});send.onclick=function(){var user=firebase.auth().currentUser,text=document.getElementById('commentText').value.trim();if(!user){window.location.href='/?returnTo='+encodeURIComponent(location.href);return;}if(!text)return;ref.push({author:user.displayName||user.email,authorUid:user.uid,text:text,timestamp:Date.now(),likes:0,parentId:null}).then(function(){document.getElementById('commentText').value='';return ref.once('value');}).then(function(s){return firebase.database().ref('sites/'+SITE+'/feed_posts/'+a.feedPostId+'/commentCount').set(s.numChildren());});};}
  document.addEventListener('DOMContentLoaded',function(){var p=path();if(categories.indexOf(p[0])<0)return;if(p.length===1)loadCategory(p[0]);else loadArticle(p[0],p[1]);});
}());
