(function(){'use strict';
  var SITE='www_metaimperiya_com',ADMINS=['ayXehcol9FgAQU6tZuup7aSaRoV2','pWB0nGVvVXc4je6466ss7IwBm9G2','ANR62p3qcjOe2ALsdVvJHUNCCV42'],form=document.getElementById('articleForm');
  function e(v){var d=document.createElement('div');d.textContent=v||'';return d.innerHTML;}
  function field(n){return document.getElementById(n);}
  function reset(){form.reset();field('articleId').value='';field('publishedAt').value=new Date().toISOString().slice(0,16);field('status').value='draft';}
  function list(){firebase.database().ref('sites/'+SITE+'/articles').once('value').then(function(s){var rows=[];s.forEach(function(c){var a=c.val();rows.push('<p><strong>'+e(a.title)+'</strong> · '+e(a.status)+' <button class="button" style="padding:5px 9px" data-edit="'+c.key+'">Редактировать</button></p>');});field('articleList').innerHTML=rows.join('')||'<p class="article-meta">Материалов пока нет.</p>';document.querySelectorAll('[data-edit]').forEach(function(b){b.onclick=function(){edit(b.dataset.edit);};});});}
  function edit(id){firebase.database().ref('sites/'+SITE+'/articles/'+id).once('value').then(function(s){var a=s.val();if(!a)return;['category','title','slug','description','coverUrl','content','status'].forEach(function(n){field(n).value=a[n]||'';});field('articleId').value=id;field('publishedAt').value=new Date(a.publishedAt||Date.now()).toISOString().slice(0,16);window.scrollTo(0,0);});}
  function save(ev){ev.preventDefault();var id=field('articleId').value||firebase.database().ref('sites/'+SITE+'/articles').push().key,cat=field('category').value,slug=field('slug').value.trim().toLowerCase(),publishedAt=new Date(field('publishedAt').value||Date.now()).getTime();if(!/^[a-z0-9-]+$/.test(slug)){alert('Slug: только латинские буквы, цифры и дефис.');return;}var ref=firebase.database().ref('sites/'+SITE+'/articles/'+id);ref.once('value').then(function(s){var old=s.val()||{};return firebase.database().ref('sites/'+SITE+'/article_slugs/'+cat+'/'+slug).once('value').then(function(slugSnap){if(slugSnap.exists()&&slugSnap.val()!==id)throw new Error('Этот slug уже используется в выбранной категории.');var article={category:cat,title:field('title').value.trim(),slug:slug,description:field('description').value.trim(),coverUrl:field('coverUrl').value.trim(),content:field('content').value,status:field('status').value,publishedAt:publishedAt,updatedAt:Date.now(),createdAt:old.createdAt||Date.now(),authorUid:firebase.auth().currentUser.uid,feedPostId:old.feedPostId||null},updates={};if(old.category&&old.slug&&(old.category!==cat||old.slug!==slug))updates['sites/'+SITE+'/article_slugs/'+old.category+'/'+old.slug]=null;updates['sites/'+SITE+'/article_slugs/'+cat+'/'+slug]=id;if(article.status==='published'){var postId=old.feedPostId;if(!postId){postId=firebase.database().ref('sites/'+SITE+'/feed_posts').push().key;article.feedPostId=postId;var user=firebase.auth().currentUser,prefix='sites/'+SITE+'/feed_posts/'+postId+'/';updates[prefix+'author']=user.displayName||user.email||'METAIMPERIYA';updates[prefix+'authorUid']=user.uid;updates[prefix+'authorAvatar']=user.photoURL||null;updates[prefix+'timestamp']=publishedAt;updates[prefix+'likes']=0;updates[prefix+'commentCount']=0;updates[prefix+'reposts']=0;updates[prefix+'articleId']=id;}var postPath='sites/'+SITE+'/feed_posts/'+postId+'/';updates[postPath+'text']=article.title;updates[postPath+'articleUrl']='/'+cat+'/'+slug+'/';updates[postPath+'articleTitle']=article.title;updates[postPath+'articleDescription']=article.description;updates[postPath+'articleCover']=article.coverUrl||null;updates[postPath+'deleted']=null;}else if(old.feedPostId){updates['sites/'+SITE+'/feed_posts/'+old.feedPostId+'/deleted']=true;}updates['sites/'+SITE+'/articles/'+id]=article;return firebase.database().ref().update(updates);});}).then(function(){alert('Сохранено.');field('articleId').value=id;list();}).catch(function(error){alert(error.message||'Не удалось сохранить материал.');});}
  function remove(){var id=field('articleId').value;if(!id||!confirm('Удалить материал?'))return;firebase.database().ref('sites/'+SITE+'/articles/'+id).once('value').then(function(s){var a=s.val()||{},u={};u['sites/'+SITE+'/articles/'+id]=null;if(a.category&&a.slug)u['sites/'+SITE+'/article_slugs/'+a.category+'/'+a.slug]=null;if(a.feedPostId)u['sites/'+SITE+'/feed_posts/'+a.feedPostId+'/deleted']=true;return firebase.database().ref().update(u);}).then(function(){reset();list();});}
  firebase.auth().onAuthStateChanged(function(u){if(!u){field('adminStatus').innerHTML='Войдите в <a href="/">социальную сеть</a>, чтобы продолжить.';return;}if(ADMINS.indexOf(u.uid)<0){field('adminStatus').textContent='У вас нет доступа к редактору.';return;}field('adminStatus').textContent='Доступ администратора подтверждён.';form.hidden=false;reset();list();});form.addEventListener('submit',save);field('newArticle').onclick=reset;field('deleteArticle').onclick=remove;
}());
